site_name: open-ST wiki
site_url: https://open.st
nav:
  - Home: index.md
  - 1. Experimental: experimental.md
  - 2. Computational: computational.md
  - FAQ: faq.md
  - About: about.md

theme:
  name: terminal